api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api/resource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: Symfony API
    version: 1.0
    show_webby: true
